<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USLBXS0062" tests="5" failures="2" timestamp="13 Sep 2017 20:14:17 GMT" time="7.505" errors="0">
  <testcase name="f" time="3.767" classname="TestSysoutFail"/>
  <testcase name="f" time="3.723" classname="TestGoogleSearch"/>
  <testcase name="test1" time="0.003" classname="TestAssertions">
    <failure type="java.lang.AssertionError" message="Test 1 has failed">
      <![CDATA[java.lang.AssertionError: Test 1 has failed
	at TestAssertions.test1(TestAssertions.java:18)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="TestAssertions"/>
  <testcase name="test3" time="0.0" classname="TestAssertions">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestAssertions.test3(TestAssertions.java:35)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite>
